server:
  port: 8764
spring:
  application:
    name: peer-eureka-three
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8763/eureka/,http://${eureka.instance.hostname}:8762/eureka/
  instance:
    hostname: localhost
