server:
  port: 8760
spring:
  application:
    name: standalone-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
