server:
  port: 8763
spring:
  application:
    name: peer-eureka-two
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8764/eureka/
  instance:
    hostname: localhost
