server:
  port: 8762
spring:
  application:
    name: peer-eureka-one
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8763/eureka/,http://${eureka.instance.hostname}:8764/eureka/
  instance:
    hostname: localhost
