spring:
  rabbitmq:
    host: 192.168.195.129
    port: 5672
    username: admin
    password: admin
  application:
    name: Demo-Timestamp-Task
logging:
  level.org.springframework.cloud.task: DEBUG
  level.org.springframework.cloud.stream: DEBUG
